kind: pipeline
name: default

steps:
- name: install
  image: composer
  commands:
  - composer install --prefer-source --no-interaction

- name: test
  image: php:7.2
  commands:
  - apt-get update
  - apt-get install -y libxml2-dev
  - docker-php-ext-install soap
  - php vendor/bin/phpunit tests

trigger:
  event: push
